=== Pkotova/CIA-world-factbook/cia.dtd
<!ELEMENT cia ( countries, regions, nations, government_types,organizations)>
	<!ELEMENT countries ( country+ )>
		<!ELEMENT country ( name,image_flag?,image_blazon?,capital,anthem?) >
			<!ATTLIST       country id 	ID 		#REQUIRED
			                region 	    IDREFS 	#REQUIRED
							nation 	    IDREFS 	#REQUIRED
			                government_type  IDREFS 	#REQUIRED 
							organization  	IDREFS 	#REQUIRED >
							
							
			<!ELEMENT name ( #PCDATA )>
            <!ELEMENT image_flag ( #PCDATA )>
            <!ELEMENT image_blazon ( #PCDATA )>
            <!ELEMENT capital ( #PCDATA )>
			<!ELEMENT anthem (song)>
				<!ELEMENT song (title, author,year)>
					<!ELEMENT title (#PCDATA)>
					<!ELEMENT author (#PCDATA)>
					<!ELEMENT year (#PCDATA)>
					
	<!ELEMENT regions (region+ )>
		<!ELEMENT region ( continent, climate, timezone+ ) >
		  <!ATTLIST region con_id ID #REQUIRED >
			<!ELEMENT continent ( #PCDATA ) >
			<!ELEMENT climate ( #PCDATA ) >
			<!ELEMENT timezone ( #PCDATA ) >
			
	<!ELEMENT nations (nation+ ) >
		<!ELEMENT nation (demonym , population, language+, religion+) >
		<!ATTLIST nation nat_id ID #REQUIRED >
		<!ELEMENT demonym  ( #PCDATA ) >
		<!ELEMENT population ( #PCDATA ) >
		<!ELEMENT language ( #PCDATA ) >
		<!ELEMENT religion ( #PCDATA ) >
			
 	<!ELEMENT government_types (government_type+ ) >
		<!ELEMENT government_type (type) >
            <!ATTLIST government_type gov_id ID #REQUIRED >
			<!ELEMENT type ( #PCDATA ) >
			
	<!ELEMENT organizations (organization+ ) >
		<!ELEMENT organization (org_name,year_establishment?) >
		  <!ATTLIST organization org_id ID #REQUIRED >
		  <!ELEMENT org_name ( #PCDATA ) >
		  <!ELEMENT year_establishment ( #PCDATA ) >

=== Pkotova/CIA-world-factbook/cia2-eu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cia SYSTEM "cia.dtd">
<cia>
	<countries>
		<country id="0000FR1" region ="WEU" nation = "FR" government_type = "GT04" organisation ="ES OON NATO">
			<name>франция</name>
			<image_flag>france_flag.png</image_flag> 
			<image_blazon>france_blazon.png</image_blazon> 
			<capital>Париж</capital>
			<anthem>
			<song>
				<title>Марсилезата</title>
					<author>Роже дьо Лил</author>
					<year>1795</year>
			</song>
				
			</anthem>
		</country>
		
		<country id="0000IT1" region ="SEU" nation = "IT" government_type = "GT03" organisation ="ES OON NATO SHEN">
			<name>Италия</name>
			<image_flag>italy_flag.png</image_flag> 
			<image_blazon>italy_blazon.png</image_blazon> 
			<capital>Рим</capital>
			<anthem>
			<song>
				<title>Химнът на Мамели</title>
				<author>Гофредо Мамели</author>
				<year>2005</year>
			</song>
				
			</anthem>
		</country>
		
		<country id="0000DE1" region ="CEU" nation = "DE" government_type = "GT03" organisation ="ES OON NATO">
			<name>Германия</name>
			<image_flag>german_flag.png</image_flag> 
			<image_blazon>german_blazon.png</image_blazon> 
			<capital>Берлин</capital>
			<anthem>
			<song>
				<title>Песента на немците</title>
				<author>Хофман фон Фалерслебен,</author>
				<year>1945</year>
			</song>
				
			</anthem>
		</country>
		
		<country id="0000DK1" region ="NEU" nation = "DK" government_type = "GT07" organisation ="ES OON NATO">
			<name>Дания</name>
			<image_flag>den_flag.png</image_flag> 
			<image_blazon>den_blazon.png</image_blazon> 
			<capital>Копенхаген</capital>
			<anthem>
				<song>
					<title>Има една прекрасна страна</title>
					<author>Адам Готлоб Йоленшлегер</author>
					<year>1835</year>
				</song>
				
			</anthem>
		</country>
		
		<country id="0000АТ1" region ="CEU" nation = "АТ" government_type = "GT04" organisation ="ES OON NATO">
			<name>Австрия</name>
			<image_flag>austria_flag.png</image_flag> 
			<image_blazon>austria_blazon.png</image_blazon> 
			<capital>Виена</capital>
			<anthem>
				<song>
					<title>Земя на планини, земя на реки</title>
					<author>Паула фон Прерадович</author>
					<year>1835</year>
				</song>
				
			</anthem>
		</country>
	</countries>	
	
	<regions>
		<region con_id="WEU">
			<continent>Западна Европа</continent>
			<climate>Умерено континентален</climate>
			<timezone>UTC+1</timezone>
		</region>
		<region con_id="SEU">
			<continent>Южна Европа</continent>
			<climate>Субтропичен</climate>
			<timezone>UTC+1</timezone>
		</region>
		<region con_id="CEU">
			<continent>Централна Европа</continent>
			<climate>Умерено континентален</climate>
			<timezone>UTC+1</timezone>
		</region>
		<region con_id="NEU">
			<continent>Северна Европа</continent>
			<climate>Умерено континентален</climate>
			<timezone>UTC+1</timezone>
		</region>
	</regions>
	
	<nations>
		<nation nat_id="DK">
			<demonym>Датчани</demonym>
			<population>5 789 957</population>
			<language>датски</language>
			<religion>лутеранство</religion>
		</nation>
		<nation nat_id="FR">
			<demonym>Французи</demonym>
			<population>67 348 000</population>
			<language>Френски</language>
			<religion>Католицизъм</religion>
		</nation>
		<nation nat_id="IT">
			<demonym>Италианци</demonym>
			<population>60 359 546</population>
			<language>Италиански</language>
			<religion>Християнство</religion>
		</nation>
		<nation nat_id="DE">
			<demonym>Германци</demonym>
			<population>83 019 200</population>
			<language>Немски </language>
			<religion>Християнство</religion>
		</nation>
		<nation nat_id="AT">
			<demonym>Австриици</demonym>
			<population>8 700 471</population>
			<language>Немски </language>
			<religion>Римокатолицизъм</religion>
		</nation>
	</nations>
	
	
<government_types>
		<government_type gov_id = "GT01">
			<type>Република</type>
		</government_type>
		
		<government_type gov_id = "GT02">
			<type>Президентска република</type>
		</government_type>
		
		<government_type gov_id = "GT03">
			<type>Парламентарна република</type>
		</government_type>
		
		<government_type gov_id = "GT04">
			<type>Полупрезидентска република</type>
		</government_type>
		
		<government_type gov_id = "GT05">
			<type>Монархия</type>
		</government_type>
		
		<government_type gov_id = "GT06">
			<type>Абсолютна монархия</type>
		</government_type>
		
		<government_type gov_id = "GT07">
			<type>Конституционна монархия</type>
		</government_type>
		
		<government_type gov_id = "GT08">
			<type>Дуалистична монархия</type>
		</government_type>
		
		<government_type gov_id = "GT09">
			<type>Парламентарна монархия</type>
		</government_type>
	</government_types>
	
	<organisations>
		<organisation org_id="NATO">
			<org_name>НАТО</org_name>
			<year_establishment>1949</year_establishment>
		</organisation>
		
		<organisation org_id="ES">
			<org_name>Европейски съюз</org_name>
			<year_establishment>1958</year_establishment>
		</organisation>
		
		<organisation org_id="NAFTA">
			<org_name>Северноамериканското споразумение за свободна търговия</org_name>
			<year_establishment>1994</year_establishment>
		</organisation>
		
		<organisation org_id="BU">
			<org_name>Британската общност</org_name>
			<year_establishment></year_establishment>
		</organisation>
		
		<organisation org_id="AU">
			<org_name>Африкански съюз</org_name>
			<year_establishment>2002</year_establishment>
		</organisation>
		
		<organisation org_id="OON">
			<org_name>Организацията на обединените нации</org_name>
			<year_establishment>1945</year_establishment>
		</organisation>
		
		<organisation org_id="BRICS">
			<org_name>БРИКС</org_name>
			<year_establishment>2009</year_establishment>
		</organisation>
		
		<organisation org_id="CPLP">
			<org_name>Организация на португалско говорящите държави</org_name>
			<year_establishment>1996</year_establishment>
		</organisation>
		<organisation org_id="SHEN">
			<org_name>Шенгенско пространство</org_name>
			<year_establishment>1985</year_establishment>
		</organisation>
		<organisation org_id="STO">
			<org_name>Световна търговска организация</org_name>
			<year_establishment>1995</year_establishment>
		</organisation>
</organisations>
	
</cia>

=== Pkotova/CIA-world-factbook/cia4-af.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cia SYSTEM "cia.dtd">
<cia>
	<countries>
		<country id="0TZ1000" region ="NAF" nation = "TZ" government_type = "GT04" organisation ="OON">
			<name>Египет</name>
			<image_flag>egypt_flag.png</image_flag> 
			<image_blazon>egypt_blazon.png</image_blazon> 
			<capital>Кайро</capital>
			<anthem>
				<song>
					<title>Родино моя, родино моя, родино моя</title>
					<author>Мохамед Юнис Ал-Кади</author>
					<year>1979</year>
				</song>
			</anthem>
		</country>
		<country id="0EG1000" region ="EAF" nation = "EG" government_type = "GT02" organisation ="OON AU">
			<name>Танзания</name>
			<image_flag>tanzania_flag.png</image_flag> 
			<image_blazon>tanzania_blazon.png</image_blazon> 
			<capital>Додома</capital>
			<anthem>
				<song>
					<title>Бог да благослови Африка</title>
					<author>Мохамед Юнис Ал-Кади</author>
					<year>1979</year>
				</song>
			</anthem>
		</country>
		<country id="0SD1000" region ="EAF" nation = "SD" government_type = "GT02" organisation ="OON AU">
			<name>Судан</name>
			<image_flag>sudan_flag.png</image_flag> 
			<image_blazon>sudan_blazon.png</image_blazon> 
			<capital>Хартум</capital>
			<anthem>
				<song>
					<title>Ние сме войници на Господ и на нашата земя</title>
					<author>Ахмад Мухамад Салих</author>
					<year>1956</year>
				</song>
			</anthem>
		</country>
		<country id="0DZ1000" region ="EAF" nation = "DZ" government_type = "GT07" organisation ="OON AU">
			<name>Алжир</name>
			<image_flag>aljir_flag.png</image_flag> 
			<image_blazon>aljir_blazon.png</image_blazon> 
			<capital>Алжир</capital>
			<anthem>
				<song>
					<title>От хората за хората</title>
					<author>	Махмуд ел Шериф</author>
					<year>1969</year>
				</song>
			</anthem>
		</country>
		<country id="0LY1000" region ="EAF" nation = "LY" government_type = "GT07" organisation ="OON AU">
			<name>Либия</name>
			<image_flag>libia_flag.png</image_flag> 
			<image_blazon>libia_blazon.png</image_blazon> 
			<capital>Триполи</capital>
			<anthem>
				<song>
					<title>Либия, Либия, Либия</title>
					<author>	Махмуд ел Шериф</author>
					<year>1969</year>
				</song>
			</anthem>
		</country>
	</countries>	
	
	<regions>
		<region con_id="NAF">
			<continent>Северна Африка</continent>
			<climate>Екваториален</climate>
			<timezone>UTC+2</timezone>
		</region>
		<region con_id="EAF">
			<continent>Източна Африка</continent>
			<climate>Тропичен</climate>
			<timezone>UTC+3</timezone>
		</region>
		
	</regions>
	
	<nations>
		<nation nat_id="EG">
			<demonym>Египтяни</demonym>
			<population>94 798 827</population>
			<language>арабски</language>
			<religion>ислям</religion>
		</nation>	
		<nation nat_id="TZ">
			<demonym>Танзаниици</demonym>
			<population>55 572 201</population>
			<language>суахили</language>
			<religion>ислям</religion>
			<religion>християнство</religion>
		</nation>
		<nation nat_id="SD">
			<demonym>Суданци</demonym>
			<population>39 578 828	</population>
			<language>арабски</language>
			<language>английски</language>
			<religion>ислям</religion>
			<religion>християнство</religion>
		</nation>
		<nation nat_id="LY">
			<demonym>Либиици</demonym>
			<population>5 670 688</population>
			<language>арабски</language>
			<religion>ислям</religion>
		</nation>
		<nation nat_id="DZ">
			<demonym>Алжирец</demonym>
			<population>42 200 000</population>
			<language>арабски</language>
			<religion>ислям</religion>
		</nation>
	</nations>
	
<government_types>
		<government_type gov_id = "GT01">
			<type>Република</type>
		</government_type>
		
		<government_type gov_id = "GT02">
			<type>Президентска република</type>
		</government_type>
		
		<government_type gov_id = "GT03">
			<type>Парламентарна република</type>
		</government_type>
		
		<government_type gov_id = "GT04">
			<type>Полупрезидентска република</type>
		</government_type>
		
		<government_type gov_id = "GT05">
			<type>Монархия</type>
		</government_type>
		
		<government_type gov_id = "GT06">
			<type>Абсолютна монархия</type>
		</government_type>
		
		<government_type gov_id = "GT07">
			<type>Конституционна монархия</type>
		</government_type>
		
		<government_type gov_id = "GT08">
			<type>Дуалистична монархия</type>
		</government_type>
		
		<government_type gov_id = "GT09">
			<type>Парламентарна монархия</type>
		</government_type>
</government_types>
	
<organisations>
		<organisation org_id="NATO">
			<org_name>НАТО</org_name>
			<year_establishment>1949</year_establishment>
		</organisation>
		
		<organisation org_id="ES">
			<org_name>Европейски съюз</org_name>
			<year_establishment>1958</year_establishment>
		</organisation>
		
		<organisation org_id="NAFTA">
			<org_name>Северноамериканското споразумение за свободна търговия</org_name>
			<year_establishment>1994</year_establishment>
		</organisation>
		
		<organisation org_id="BU">
			<org_name>Британската общност</org_name>
			<year_establishment></year_establishment>
		</organisation>
		
		<organisation org_id="AU">
			<org_name>Африкански съюз</org_name>
			<year_establishment>2002</year_establishment>
		</organisation>
		
		<organisation org_id="OON">
			<org_name>Организацията на обединените нации</org_name>
			<year_establishment>1945</year_establishment>
		</organisation>
		
		<organisation org_id="BRICS">
			<org_name>БРИКС</org_name>
			<year_establishment>2009</year_establishment>
		</organisation>
		
		<organisation org_id="CPLP">
			<org_name>Организация на португалско говорящите държави</org_name>
			<year_establishment>1996</year_establishment>
		</organisation>
		<organisation org_id="SHEN">
			<org_name>Шенгенско пространство</org_name>
			<year_establishment>1985</year_establishment>
		</organisation>
		<organisation org_id="STO">
			<org_name>Световна търговска организация</org_name>
			<year_establishment>1995</year_establishment>
		</organisation>
</organisations>
	
</cia>

=== Pkotova/CIA-world-factbook/cia5-na.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cia SYSTEM "cia.dtd">
<cia>
	<countries>
		<country id="01US000" region ="CNA" nation = "JP" government_type = "GT02" organisation ="OON NAFTA NATO">
			<name>Съединени Американски Щати</name>
			<image_flag>usa_flag.png</image_flag> 
			<image_blazon>usa_blazon.png</image_blazon> 
			<capital>Вашингтон</capital>
			<anthem>
				<song>
					<title>Знаме, обсипано със звезди</title>
					<author>Знаме, обсипано със звезди</author>
					<year>1931</year>
				</song>
			</anthem>
		</country>
		<country id="01MX000" region ="SNA" nation = "MX" government_type = "GT02" organisation ="OON NAFTA">
			<name>Мексико</name>
			<image_flag>mexico_flag.png</image_flag> 
			<image_blazon>mexico_blazon.png</image_blazon> 
			<capital>Мексико</capital>
			<anthem>
				<song>
					<title>Национален химн на Мексико</title>
					<author>Знаме, обсипано със звезди</author>
					<year>1931</year>
				</song>
			</anthem>
		</country>
	
	</countries>	
	
	<regions>
		<region con_id="CNA">
			<continent>Централна Северна Америка</continent>
			<climate>Умерено континентален</climate>
			<timezone>UTC-9</timezone>
		</region>
		
		<region con_id="SNA">
			<continent>Южна Северна Америка</continent>
			<climate>Умерено континентален</climate>
			<timezone>UTC-9</timezone>
		</region>
		
		
	</regions>
	
	<nations>
		<nation nat_id="MX">
			<demonym>Мексиканци</demonym>
			<population>127 094 745</population>
			<language>испански</language>
			<religion>католицизъм</religion>
		</nation>
		
		<nation nat_id="US">
		
			<demonym>Американци</demonym>
			<population>308 745 538</population>
			<language>английски</language>
			<religion>християнство</religion>
		</nation>
		
	</nations>
	
<government_types>
		<government_type gov_id = "GT01">
			<type>Република</type>
		</government_type>
		
		<government_type gov_id = "GT02">
			<type>Президентска република</type>
		</government_type>
		
		<government_type gov_id = "GT03">
			<type>Парламентарна република</type>
		</government_type>
		
		<government_type gov_id = "GT04">
			<type>Полупрезидентска република</type>
		</government_type>
		
		<government_type gov_id = "GT05">
			<type>Монархия</type>
		</government_type>
		
		<government_type gov_id = "GT06">
			<type>Абсолютна монархия</type>
		</government_type>
		
		<government_type gov_id = "GT07">
			<type>Конституционна монархия</type>
		</government_type>
		
		<government_type gov_id = "GT08">
			<type>Дуалистична монархия</type>
		</government_type>
		
		<government_type gov_id = "GT09">
			<type>Парламентарна монархия</type>
		</government_type>
	</government_types>
	
	<organisations>
		<organisation org_id="NATO">
			<org_name>НАТО</org_name>
			<year_establishment>1949</year_establishment>
		</organisation>
		
		<organisation org_id="ES">
			<org_name>Европейски съюз</org_name>
			<year_establishment>1958</year_establishment>
		</organisation>
		
		<organisation org_id="NAFTA">
			<org_name>Северноамериканското споразумение за свободна търговия</org_name>
			<year_establishment>1994</year_establishment>
		</organisation>
		
		<organisation org_id="BU">
			<org_name>Британската общност</org_name>
			<year_establishment></year_establishment>
		</organisation>
		
		<organisation org_id="AU">
			<org_name>Африкански съюз</org_name>
			<year_establishment>2002</year_establishment>
		</organisation>
		
		<organisation org_id="OON">
			<org_name>Организацията на обединените нации</org_name>
			<year_establishment>1945</year_establishment>
		</organisation>
		
		<organisation org_id="BRICS">
			<org_name>БРИКС</org_name>
			<year_establishment>2009</year_establishment>
		</organisation>
		
		<organisation org_id="CPLP">
			<org_name>Организация на португалско говорящите държави</org_name>
			<year_establishment>1996</year_establishment>
		</organisation>
		<organisation org_id="SHEN">
			<org_name>Шенгенско пространство</org_name>
			<year_establishment>1985</year_establishment>
		</organisation>
		<organisation org_id="STO">
			<org_name>Световна търговска организация</org_name>
			<year_establishment>1995</year_establishment>
		</organisation>
</organisations>
	
</cia>

=== Pkotova/CIA-world-factbook/cia6-sa.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cia SYSTEM "cia.dtd">
<cia>
	<countries>
		<country id="001АR00" region ="SSA" nation = "AR" government_type = "GT02" organisation ="OON NAFTA NATO STO">
			<name>Аржентина</name>
			<image_flag>argentina_flag.png</image_flag> 
			<image_blazon>argentina_blazon.png</image_blazon> 
			<capital>Буенос Айрес</capital>
			<anthem>
				<song>
					<title>Химн на Аржентина</title>
					<author>Блас Парера</author>
					<year>1813</year>
				</song>
			</anthem>
		</country>
		<country id="001PE00" region ="WSA" nation = "PE" government_type = "GT02" organisation ="OON">
			<name>Перу</name>
			<image_flag>peru_flag.png</image_flag> 
			<image_blazon>peru_blazon.png</image_blazon> 
			<capital>Лима</capital>
			<anthem>
				<song>
					<title>Химн на Перу</title>
					<author>Блас Парера</author>
					<year>1813</year>
				</song>
			</anthem>
		</country>
		<country id="001EC00" region ="WSA" nation = "EC" government_type = "GT02" organisation ="OON">
			<name>Еквадор</name>
			<image_flag>eq_flag.png</image_flag> 
			<image_blazon>eq_blazon.png</image_blazon> 
			<capital>Кито</capital>
			<anthem>
				<song>
					<title>Здравей, О, Родина</title>
					<author>Блас Парера</author>
					<year>1813</year>
				</song>
			</anthem>
		</country>
		<country id="001CL00" region ="WSA" nation = "CL" government_type = "GT02" organisation ="OON">
			<name>Чили</name>
			<image_flag>chilli_flag.png</image_flag> 
			<image_blazon>chilli_blazon.png</image_blazon> 
			<capital>Сантяго</capital>
			<anthem>
				<song>
					<title>Национален химн на Чили</title>
					<author>Блас Парера</author>
					<year>1813</year>
				</song>
			</anthem>
		</country>
		<country id="001UR00" region ="ESA" nation = "UR" government_type = "GT02" organisation ="OON">
			<name>Уругвай</name>
			<image_flag>uru_flag.png</image_flag> 
			<image_blazon>uru_blazon.png</image_blazon> 
			<capital>Монтевидео</capital>
			<anthem>
				<song>
					<title>Национален химн на Уругвай</title>
					<author>Блас Парера</author>
					<year>1813</year>
				</song>
			</anthem>
		</country>
	</countries>	
	
	<regions>
		<region con_id="SSA">
			<continent>Южна Южна Америка</continent>
			<climate>Умерено континентален</climate>
			<timezone>UTC-9</timezone>
		</region>
		<region con_id="WSA">
			<continent>Западна Южна Америка</continent>
			<climate>Тропичен</climate>
			<timezone>UTC-5</timezone>
		</region>
		<region con_id="ЕSA">
			<continent>Източна Южна Америка</continent>
			<climate>Тропичен</climate>
			<timezone>UTC-3</timezone>
		</region>	
	</regions>
	
	<nations>
		<nation nat_id="AR">
			<demonym>Аржентинци</demonym>
			<population>40 117 096</population>
			<language>испански</language>
			<religion>римокатолицизъм</religion>
		</nation>	
		<nation nat_id="PE">
		
			<demonym>Перуканци</demonym>
			<population>32 162 184</population>
			<language>испански</language>
			<religion>римокатолицизъм</religion>
		</nation>		
		<nation nat_id="EC">
			<demonym>Еквадорци</demonym>
			<population>16 144 000</population>
			<language>испански</language>
			<religion>римокатолицизъм</religion>
		</nation>		
		<nation nat_id="CL">
			<demonym>Чилиици</demonym>
			<population>17 574 003</population>
			<language>испански</language>
			<religion>християнство</religion>
		</nation>
		<nation nat_id="UR">
			<demonym>Уругвайци</demonym>
			<population>17 574 003</population>
			<language>испански</language>
			<religion>християнство</religion>
		</nation>

		
	</nations>
	
	<government_types>
		<government_type gov_id = "GT01">
			<type>Република</type>
		</government_type>
		
		<government_type gov_id = "GT02">
			<type>Президентска република</type>
		</government_type>
		
		<government_type gov_id = "GT03">
			<type>Парламентарна република</type>
		</government_type>
		
		<government_type gov_id = "GT04">
			<type>Полупрезидентска република</type>
		</government_type>
		
		<government_type gov_id = "GT05">
			<type>Монархия</type>
		</government_type>
		
		<government_type gov_id = "GT06">
			<type>Абсолютна монархия</type>
		</government_type>
		
		<government_type gov_id = "GT07">
			<type>Конституционна монархия</type>
		</government_type>
		
		<government_type gov_id = "GT08">
			<type>Дуалистична монархия</type>
		</government_type>
		
		<government_type gov_id = "GT09">
			<type>Парламентарна монархия</type>
		</government_type>
	</government_types>
	
	<organisations>
		<organisation org_id="NATO">
			<org_name>НАТО</org_name>
			<year_establishment>1949</year_establishment>
		</organisation>
		
		<organisation org_id="ES">
			<org_name>Европейски съюз</org_name>
			<year_establishment>1958</year_establishment>
		</organisation>
		
		<organisation org_id="NAFTA">
			<org_name>Северноамериканското споразумение за свободна търговия</org_name>
			<year_establishment>1994</year_establishment>
		</organisation>
		
		<organisation org_id="BU">
			<org_name>Британската общност</org_name>
			<year_establishment></year_establishment>
		</organisation>
		
		<organisation org_id="AU">
			<org_name>Африкански съюз</org_name>
			<year_establishment>2002</year_establishment>
		</organisation>
		
		<organisation org_id="OON">
			<org_name>Организацията на обединените нации</org_name>
			<year_establishment>1945</year_establishment>
		</organisation>
		
		<organisation org_id="BRICS">
			<org_name>БРИКС</org_name>
			<year_establishment>2009</year_establishment>
		</organisation>
		
		<organisation org_id="CPLP">
			<org_name>Организация на португалско говорящите държави</org_name>
			<year_establishment>1996</year_establishment>
		</organisation>
		<organisation org_id="SHEN">
			<org_name>Шенгенско пространство</org_name>
			<year_establishment>1985</year_establishment>
		</organisation>
		<organisation org_id="STO">
			<org_name>Световна търговска организация</org_name>
			<year_establishment>1995</year_establishment>
		</organisation>
	</organisations>
	
</cia>
