=== Pkotova/CIA-world-factbook/cia.dtd
<!ELEMENT cia ( countries, regions, nations, government_types,organizations)>
	<!ELEMENT countries ( country+ )>
		<!ELEMENT country ( name,image_flag?,image_blazon?,capital,anthem?) >
			<!ATTLIST       country id 	ID 		#REQUIRED
			                region 	    IDREFS 	#REQUIRED
							nation 	    IDREFS 	#REQUIRED
			                government_type  IDREFS 	#REQUIRED 
							organization  	IDREFS 	#REQUIRED >
							
							
			<!ELEMENT name ( #PCDATA )>
            <!ELEMENT image_flag ( #PCDATA )>
            <!ELEMENT image_blazon ( #PCDATA )>
            <!ELEMENT capital ( #PCDATA )>
			<!ELEMENT anthem (song)>
				<!ELEMENT song (title, author,year)>
					<!ELEMENT title (#PCDATA)>
					<!ELEMENT author (#PCDATA)>
					<!ELEMENT year (#PCDATA)>
					
	<!ELEMENT regions (region+ )>
		<!ELEMENT region ( continent, climate, timezone+ ) >
		  <!ATTLIST region con_id ID #REQUIRED >
			<!ELEMENT continent ( #PCDATA ) >
			<!ELEMENT climate ( #PCDATA ) >
			<!ELEMENT timezone ( #PCDATA ) >
			
	<!ELEMENT nations (nation+ ) >
		<!ELEMENT nation (demonym , population, language+, religion+) >
		<!ATTLIST nation nat_id ID #REQUIRED >
		<!ELEMENT demonym  ( #PCDATA ) >
		<!ELEMENT population ( #PCDATA ) >
		<!ELEMENT language ( #PCDATA ) >
		<!ELEMENT religion ( #PCDATA ) >
			
 	<!ELEMENT government_types (government_type+ ) >
		<!ELEMENT government_type (type) >
            <!ATTLIST government_type gov_id ID #REQUIRED >
			<!ELEMENT type ( #PCDATA ) >
			
	<!ELEMENT organizations (organization+ ) >
		<!ELEMENT organization (org_name,year_establishment?) >
		  <!ATTLIST organization org_id ID #REQUIRED >
		  <!ELEMENT org_name ( #PCDATA ) >
		  <!ELEMENT year_establishment ( #PCDATA ) >

=== Pkotova/CIA-world-factbook/cia3-as.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cia SYSTEM "cia.dtd">
<cia>
	<countries>
		<country id="00JP100" region ="EAS" nation = "JP" government_type = "GT07" organisation ="OON">
			<name>Япония</name>
			<image_flag>japan_flag.png</image_flag> 
			<image_blazon>japan_blazon.png</image_blazon> 
			<capital>Токио</capital>
			<anthem>
				<song>
					<title>Кимигайо</title>
					<author>Франц Екерт</author>
					<year>1880</year>
				</song>
			</anthem>
		</country>
		
		<country id="00ID100" region ="SAS" nation = "ID" government_type = "GT02" organisation ="OON">
			<name>Индонезия</name>
			<image_flag>indonesia_flag.png</image_flag> 
			<image_blazon>indonesia_blazon.png</image_blazon> 
			<capital>Джакарта</capital>
			<anthem>
				<song>
					<title>Раят Индонезия</title>
					<author>Франц Екерт</author>
					<year>1880</year>
				</song>
			</anthem>
		</country>
		
		<country id="00IN100" region ="SAS" nation = "IN" government_type = "GT03" organisation ="OON BRICS STO">
			<name>Индия</name>
			<image_flag>india_flag.png</image_flag> 
			<image_blazon>india_blazon.png</image_blazon> 
			<capital>Ню Делхи</capital>
			<anthem>
				<song>
					<title>Ти си на началника на съзнанието на всички хора</title>
					<author>Рабиндранат Тагор</author>
					<year>1950</year>
				</song>
			</anthem>
		</country>
		
		<country id="00IQ100" region ="WAS" nation = "IQ" government_type = "GT03" organisation ="OON">
			<name>Ирак</name>
			<image_flag>iraq_flag.png</image_flag> 
			<image_blazon>iraq_blazon.png</image_blazon> 
			<capital>Багдад</capital>
			<anthem>
				<song>
					<title>Моята родина</title>
					<author>Ибрахим Тукан</author>
					<year>2004</year>
				</song>
			</anthem>
		</country>
		
		<country id="00VN100" region ="SAS" nation = "VN" government_type = "GT01" organisation ="OON">
			<name>Виетнам</name>
			<image_flag>vietnam_flag.png</image_flag> 
			<image_blazon>vietnam_blazon.png</image_blazon> 
			<capital>Ханой</capital>
			<anthem>
				<song>
					<title>Моята родина</title>
					<author>Ван Као</author>
					<year>1976</year>
				</song>
			</anthem>
		</country>
	</countries>	
	
	<regions>
		<region con_id="EAS">
			<demonym>Източна Азия</demonym>
			<climate>Умерено континентален</climate>
			<timezone>UTC+9</timezone>
		</region>
		
		<region con_id="SAS">
			<demonym>Южна Азия</demonym>
			<climate>Тропичен</climate>
			<timezone>UTC+7</timezone>
		</region>
		
		<region con_id="WAS">
			<demonym>Западна Азия</demonym>
			<climate>Тропичен</climate>
			<timezone>UTC+3</timezone>
		</region>
		
	</regions>
	
	<nations>
		<nation nat_id="JP">
			<demonym>Японци</demonym>
			<population>127 094 745</population>
			<language>японски</language>
			<religion>шинтоизъм</religion>
			<religion>будъзъм</religion>
		</nation>
		
		<nation nat_id="ID">
		
			<demonym>Индонезиици</demonym>
			<population>237 641 326</population>
			<language>индонезииски</language>
			<religion>ислям</religion>
			<religion>християнство</religion>
		</nation>
		
		<nation nat_id="IN">
			<demonym>Индиици</demonym>
			<population>1 210 854 977</population>
			<language>хинди</language>
			<religion>индуизъм</religion>
		</nation>
		
		<nation nat_id="IQ">
			<demonym>Иракчани</demonym>
			<population>37 202 572</population>
			<language>арабски</language>
			<language>кюрдски</language>
			<religion>ислям</religion>
		</nation>

		<nation nat_id="VN">
			<demonym>Виетнамци</demonym>
			<population>96 208 984</population>
			<language>виетнамски</language>
			<language>християнство</language>
		</nation>
	</nations>
	
		
<government_types>
		<government_type gov_id = "GT01">
			<type>Република</type>
		</government_type>
		
		<government_type gov_id = "GT02">
			<type>Президентска република</type>
		</government_type>
		
		<government_type gov_id = "GT03">
			<type>Парламентарна република</type>
		</government_type>
		
		<government_type gov_id = "GT04">
			<type>Полупрезидентска република</type>
		</government_type>
		
		<government_type gov_id = "GT05">
			<type>Монархия</type>
		</government_type>
		
		<government_type gov_id = "GT06">
			<type>Абсолютна монархия</type>
		</government_type>
		
		<government_type gov_id = "GT07">
			<type>Конституционна монархия</type>
		</government_type>
		
		<government_type gov_id = "GT08">
			<type>Дуалистична монархия</type>
		</government_type>
		
		<government_type gov_id = "GT09">
			<type>Парламентарна монархия</type>
		</government_type>
	</government_types>
	
	<organisations>
		<organisation org_id="NATO">
			<org_name>НАТО</org_name>
			<year_establishment>1949</year_establishment>
		</organisation>
		
		<organisation org_id="ES">
			<org_name>Европейски съюз</org_name>
			<year_establishment>1958</year_establishment>
		</organisation>
		
		<organisation org_id="NAFTA">
			<org_name>Северноамериканското споразумение за свободна търговия</org_name>
			<year_establishment>1994</year_establishment>
		</organisation>
		
		<organisation org_id="BU">
			<org_name>Британската общност</org_name>
			<year_establishment></year_establishment>
		</organisation>
		
		<organisation org_id="AU">
			<org_name>Африкански съюз</org_name>
			<year_establishment>2002</year_establishment>
		</organisation>
		
		<organisation org_id="OON">
			<org_name>Организацията на обединените нации</org_name>
			<year_establishment>1945</year_establishment>
		</organisation>
		
		<organisation org_id="BRICS">
			<org_name>БРИКС</org_name>
			<year_establishment>2009</year_establishment>
		</organisation>
		
		<organisation org_id="CPLP">
			<org_name>Организация на португалско говорящите държави</org_name>
			<year_establishment>1996</year_establishment>
		</organisation>
		<organisation org_id="SHEN">
			<org_name>Шенгенско пространство</org_name>
			<year_establishment>1985</year_establishment>
		</organisation>
		<organisation org_id="STO">
			<org_name>Световна търговска организация</org_name>
			<year_establishment>1995</year_establishment>
		</organisation>
</organisations>
</cia>
